/* Generated by Yosys 0.20+22 (git sha1 UNKNOWN, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module locked(inputs, key, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  input [7:0] inputs;
  wire [7:0] inputs;
  input [7:0] key;
  wire [7:0] key;
  output out;
  wire out;
  wire [3:0] \s.c.a ;
  wire [3:0] \s.c.b ;
  wire [4:0] \s.c.c ;
  wire [4:0] \s.ckt_out ;
  wire [7:0] \s.inputs ;
  wire [7:0] \s.key ;
  wire \s.keyx ;
  wire \s.lock_out ;
  NOT_g _36_ (
    .A(inputs[3]),
    .Y(_00_)
  );
  XNOR_g _37_ (
    .A(inputs[0]),
    .B(key[0]),
    .Y(_01_)
  );
  XNOR_g _38_ (
    .A(inputs[7]),
    .B(key[7]),
    .Y(_02_)
  );
  AND_g _39_ (
    .A(_01_),
    .B(_02_),
    .Y(_03_)
  );
  XNOR_g _40_ (
    .A(inputs[1]),
    .B(key[1]),
    .Y(_04_)
  );
  XNOR_g _41_ (
    .A(inputs[3]),
    .B(key[3]),
    .Y(_05_)
  );
  AND_g _42_ (
    .A(_04_),
    .B(_05_),
    .Y(_06_)
  );
  AND_g _43_ (
    .A(_03_),
    .B(_06_),
    .Y(_07_)
  );
  NOR_g _44_ (
    .A(inputs[5]),
    .B(inputs[6]),
    .Y(_08_)
  );
  NOR_g _45_ (
    .A(inputs[4]),
    .B(inputs[7]),
    .Y(_09_)
  );
  AND_g _46_ (
    .A(_08_),
    .B(_09_),
    .Y(_10_)
  );
  NOR_g _47_ (
    .A(inputs[1]),
    .B(inputs[2]),
    .Y(_11_)
  );
  AND_g _48_ (
    .A(inputs[0]),
    .B(_00_),
    .Y(_12_)
  );
  AND_g _49_ (
    .A(_11_),
    .B(_12_),
    .Y(_13_)
  );
  NAND_g _50_ (
    .A(_10_),
    .B(_13_),
    .Y(_14_)
  );
  XNOR_g _51_ (
    .A(inputs[5]),
    .B(key[5]),
    .Y(_15_)
  );
  XNOR_g _52_ (
    .A(inputs[2]),
    .B(key[2]),
    .Y(_16_)
  );
  AND_g _53_ (
    .A(_15_),
    .B(_16_),
    .Y(_17_)
  );
  XNOR_g _54_ (
    .A(inputs[6]),
    .B(key[6]),
    .Y(_18_)
  );
  XNOR_g _55_ (
    .A(inputs[4]),
    .B(key[4]),
    .Y(_19_)
  );
  AND_g _56_ (
    .A(_18_),
    .B(_19_),
    .Y(_20_)
  );
  AND_g _57_ (
    .A(_17_),
    .B(_20_),
    .Y(_21_)
  );
  AND_g _58_ (
    .A(_14_),
    .B(_21_),
    .Y(_22_)
  );
  NAND_g _59_ (
    .A(_07_),
    .B(_22_),
    .Y(_23_)
  );
  XNOR_g _60_ (
    .A(\s.c.c [0]),
    .B(_23_),
    .Y(out)
  );
  AND_g _61_ (
    .A(inputs[0]),
    .B(inputs[4]),
    .Y(_24_)
  );
  NAND_g _62_ (
    .A(inputs[1]),
    .B(inputs[5]),
    .Y(_25_)
  );
  XOR_g _63_ (
    .A(inputs[1]),
    .B(inputs[5]),
    .Y(_26_)
  );
  NAND_g _64_ (
    .A(_24_),
    .B(_26_),
    .Y(_27_)
  );
  XOR_g _65_ (
    .A(_24_),
    .B(_26_),
    .Y(\s.c.c [1])
  );
  NAND_g _66_ (
    .A(_25_),
    .B(_27_),
    .Y(_28_)
  );
  NAND_g _67_ (
    .A(inputs[2]),
    .B(inputs[6]),
    .Y(_29_)
  );
  XOR_g _68_ (
    .A(inputs[2]),
    .B(inputs[6]),
    .Y(_30_)
  );
  NAND_g _69_ (
    .A(_28_),
    .B(_30_),
    .Y(_31_)
  );
  XOR_g _70_ (
    .A(_28_),
    .B(_30_),
    .Y(\s.c.c [2])
  );
  NAND_g _71_ (
    .A(_29_),
    .B(_31_),
    .Y(_32_)
  );
  NAND_g _72_ (
    .A(inputs[3]),
    .B(inputs[7]),
    .Y(_33_)
  );
  XOR_g _73_ (
    .A(inputs[3]),
    .B(inputs[7]),
    .Y(_34_)
  );
  NAND_g _74_ (
    .A(_32_),
    .B(_34_),
    .Y(_35_)
  );
  XOR_g _75_ (
    .A(_32_),
    .B(_34_),
    .Y(\s.c.c [3])
  );
  XOR_g _76_ (
    .A(inputs[0]),
    .B(inputs[4]),
    .Y(\s.c.c [0])
  );
  NAND_g _77_ (
    .A(_33_),
    .B(_35_),
    .Y(\s.c.c [4])
  );
  assign \s.ckt_out  = \s.c.c ;
  assign \s.inputs  = inputs;
  assign \s.key  = key;
  assign \s.keyx  = 1'h1;
  assign \s.lock_out  = out;
  assign \s.c.a  = inputs[3:0];
  assign \s.c.b  = inputs[7:4];
endmodule
