/* Generated by Yosys 0.20+22 (git sha1 UNKNOWN, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module test_adder(NODEA, NODEB, NODEC);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  input [0:7] NODEA;
  wire [0:7] NODEA;
  input [0:7] NODEB;
  wire [0:7] NODEB;
  output [0:16] NODEC;
  wire [0:16] NODEC;
  wire [3:0] \mootop.Addend0 ;
  wire [3:0] \mootop.Addend1 ;
  wire [3:0] \mootop.Addend2 ;
  wire [3:0] \mootop.Augend0 ;
  wire \mootop.Carry0 ;
  wire \mootop.Carry1 ;
  wire [3:0] \mootop.Sum0 ;
  wire [3:0] \mootop.Sum1 ;
  wire \mootop.rc0.C0 ;
  wire \mootop.rc0.C1 ;
  wire \mootop.rc0.C2 ;
  wire \mootop.rc1.C0 ;
  wire \mootop.rc1.C1 ;
  wire \mootop.rc1.C2 ;
  wire \mootop.rc2.C0 ;
  wire \mootop.rc2.C1 ;
  wire \mootop.rc2.C2 ;
  AND_g _077_ (
    .A(NODEA[7]),
    .B(NODEB[7]),
    .Y(_000_)
  );
  NAND_g _078_ (
    .A(NODEA[6]),
    .B(NODEB[6]),
    .Y(_001_)
  );
  XOR_g _079_ (
    .A(NODEA[6]),
    .B(NODEB[6]),
    .Y(_002_)
  );
  NAND_g _080_ (
    .A(_000_),
    .B(_002_),
    .Y(_003_)
  );
  XOR_g _081_ (
    .A(_000_),
    .B(_002_),
    .Y(NODEC[15])
  );
  NAND_g _082_ (
    .A(_001_),
    .B(_003_),
    .Y(_004_)
  );
  NAND_g _083_ (
    .A(NODEA[5]),
    .B(NODEB[5]),
    .Y(_005_)
  );
  XOR_g _084_ (
    .A(NODEA[5]),
    .B(NODEB[5]),
    .Y(_006_)
  );
  NAND_g _085_ (
    .A(_004_),
    .B(_006_),
    .Y(_007_)
  );
  XOR_g _086_ (
    .A(_004_),
    .B(_006_),
    .Y(NODEC[14])
  );
  NAND_g _087_ (
    .A(_005_),
    .B(_007_),
    .Y(_008_)
  );
  NAND_g _088_ (
    .A(NODEA[4]),
    .B(NODEB[4]),
    .Y(_009_)
  );
  XOR_g _089_ (
    .A(NODEA[4]),
    .B(NODEB[4]),
    .Y(_010_)
  );
  NAND_g _090_ (
    .A(_008_),
    .B(_010_),
    .Y(_011_)
  );
  XOR_g _091_ (
    .A(_008_),
    .B(_010_),
    .Y(NODEC[13])
  );
  NAND_g _092_ (
    .A(_009_),
    .B(_011_),
    .Y(_012_)
  );
  NAND_g _093_ (
    .A(NODEA[3]),
    .B(NODEB[3]),
    .Y(_013_)
  );
  XOR_g _094_ (
    .A(NODEA[3]),
    .B(NODEB[3]),
    .Y(_014_)
  );
  NAND_g _095_ (
    .A(_012_),
    .B(_014_),
    .Y(_015_)
  );
  XOR_g _096_ (
    .A(_012_),
    .B(_014_),
    .Y(NODEC[12])
  );
  NAND_g _097_ (
    .A(_013_),
    .B(_015_),
    .Y(_016_)
  );
  NAND_g _098_ (
    .A(NODEA[2]),
    .B(NODEB[2]),
    .Y(_017_)
  );
  XOR_g _099_ (
    .A(NODEA[2]),
    .B(NODEB[2]),
    .Y(_018_)
  );
  NAND_g _100_ (
    .A(_016_),
    .B(_018_),
    .Y(_019_)
  );
  XOR_g _101_ (
    .A(_016_),
    .B(_018_),
    .Y(NODEC[11])
  );
  NAND_g _102_ (
    .A(_017_),
    .B(_019_),
    .Y(_020_)
  );
  NAND_g _103_ (
    .A(NODEA[1]),
    .B(NODEB[1]),
    .Y(_021_)
  );
  XOR_g _104_ (
    .A(NODEA[1]),
    .B(NODEB[1]),
    .Y(_022_)
  );
  NAND_g _105_ (
    .A(_020_),
    .B(_022_),
    .Y(_023_)
  );
  XOR_g _106_ (
    .A(_020_),
    .B(_022_),
    .Y(NODEC[10])
  );
  AND_g _107_ (
    .A(_021_),
    .B(_023_),
    .Y(_024_)
  );
  NAND_g _108_ (
    .A(NODEA[0]),
    .B(NODEB[0]),
    .Y(_025_)
  );
  NOR_g _109_ (
    .A(NODEA[0]),
    .B(NODEB[0]),
    .Y(_026_)
  );
  XOR_g _110_ (
    .A(NODEA[0]),
    .B(NODEB[0]),
    .Y(_027_)
  );
  XNOR_g _111_ (
    .A(_024_),
    .B(_027_),
    .Y(NODEC[9])
  );
  XOR_g _112_ (
    .A(NODEA[7]),
    .B(NODEB[7]),
    .Y(NODEC[16])
  );
  AND_g _113_ (
    .A(_024_),
    .B(_025_),
    .Y(_028_)
  );
  NOR_g _114_ (
    .A(_026_),
    .B(_028_),
    .Y(NODEC[8])
  );
  AND_g _115_ (
    .A(NODEA[3]),
    .B(NODEB[3]),
    .Y(NODEC[7])
  );
  AND_g _116_ (
    .A(NODEB[3]),
    .B(NODEA[2]),
    .Y(\mootop.Augend0 [0])
  );
  AND_g _117_ (
    .A(NODEB[3]),
    .B(NODEA[1]),
    .Y(\mootop.Augend0 [1])
  );
  AND_g _118_ (
    .A(NODEB[3]),
    .B(NODEA[0]),
    .Y(\mootop.Augend0 [2])
  );
  AND_g _119_ (
    .A(NODEA[3]),
    .B(NODEB[2]),
    .Y(\mootop.Addend0 [0])
  );
  AND_g _120_ (
    .A(NODEA[2]),
    .B(NODEB[2]),
    .Y(\mootop.Addend0 [1])
  );
  AND_g _121_ (
    .A(NODEA[1]),
    .B(NODEB[2]),
    .Y(\mootop.Addend0 [2])
  );
  AND_g _122_ (
    .A(NODEA[0]),
    .B(NODEB[2]),
    .Y(\mootop.Addend0 [3])
  );
  AND_g _123_ (
    .A(NODEA[3]),
    .B(NODEB[1]),
    .Y(\mootop.Addend1 [0])
  );
  AND_g _124_ (
    .A(NODEA[2]),
    .B(NODEB[1]),
    .Y(\mootop.Addend1 [1])
  );
  AND_g _125_ (
    .A(NODEA[1]),
    .B(NODEB[1]),
    .Y(\mootop.Addend1 [2])
  );
  AND_g _126_ (
    .A(NODEA[0]),
    .B(NODEB[1]),
    .Y(\mootop.Addend1 [3])
  );
  AND_g _127_ (
    .A(NODEA[3]),
    .B(NODEB[0]),
    .Y(\mootop.Addend2 [0])
  );
  AND_g _128_ (
    .A(NODEA[2]),
    .B(NODEB[0]),
    .Y(\mootop.Addend2 [1])
  );
  AND_g _129_ (
    .A(NODEA[1]),
    .B(NODEB[0]),
    .Y(\mootop.Addend2 [2])
  );
  AND_g _130_ (
    .A(NODEA[0]),
    .B(NODEB[0]),
    .Y(\mootop.Addend2 [3])
  );
  NOR_g _131_ (
    .A(\mootop.Augend0 [0]),
    .B(1'h0),
    .Y(_029_)
  );
  AND_g _132_ (
    .A(\mootop.Augend0 [0]),
    .B(1'h0),
    .Y(_030_)
  );
  XNOR_g _133_ (
    .A(\mootop.Augend0 [0]),
    .B(1'h0),
    .Y(_031_)
  );
  NOR_g _134_ (
    .A(\mootop.Addend0 [0]),
    .B(_030_),
    .Y(_032_)
  );
  NOR_g _135_ (
    .A(_029_),
    .B(_032_),
    .Y(\mootop.rc0.C0 )
  );
  XNOR_g _136_ (
    .A(\mootop.Addend0 [0]),
    .B(_031_),
    .Y(NODEC[6])
  );
  NOR_g _137_ (
    .A(\mootop.Augend0 [1]),
    .B(\mootop.rc0.C0 ),
    .Y(_033_)
  );
  AND_g _138_ (
    .A(\mootop.Augend0 [1]),
    .B(\mootop.rc0.C0 ),
    .Y(_034_)
  );
  XNOR_g _139_ (
    .A(\mootop.Augend0 [1]),
    .B(\mootop.rc0.C0 ),
    .Y(_035_)
  );
  NOR_g _140_ (
    .A(\mootop.Addend0 [1]),
    .B(_034_),
    .Y(_036_)
  );
  NOR_g _141_ (
    .A(_033_),
    .B(_036_),
    .Y(\mootop.rc0.C1 )
  );
  XNOR_g _142_ (
    .A(\mootop.Addend0 [1]),
    .B(_035_),
    .Y(\mootop.Sum0 [1])
  );
  NOR_g _143_ (
    .A(\mootop.Augend0 [2]),
    .B(\mootop.rc0.C1 ),
    .Y(_037_)
  );
  AND_g _144_ (
    .A(\mootop.Augend0 [2]),
    .B(\mootop.rc0.C1 ),
    .Y(_038_)
  );
  XNOR_g _145_ (
    .A(\mootop.Augend0 [2]),
    .B(\mootop.rc0.C1 ),
    .Y(_039_)
  );
  NOR_g _146_ (
    .A(\mootop.Addend0 [2]),
    .B(_038_),
    .Y(_040_)
  );
  NOR_g _147_ (
    .A(_037_),
    .B(_040_),
    .Y(\mootop.rc0.C2 )
  );
  XNOR_g _148_ (
    .A(\mootop.Addend0 [2]),
    .B(_039_),
    .Y(\mootop.Sum0 [2])
  );
  NOR_g _149_ (
    .A(1'h0),
    .B(\mootop.rc0.C2 ),
    .Y(_041_)
  );
  AND_g _150_ (
    .A(1'h0),
    .B(\mootop.rc0.C2 ),
    .Y(_042_)
  );
  XNOR_g _151_ (
    .A(1'h0),
    .B(\mootop.rc0.C2 ),
    .Y(_043_)
  );
  NOR_g _152_ (
    .A(\mootop.Addend0 [3]),
    .B(_042_),
    .Y(_044_)
  );
  NOR_g _153_ (
    .A(_041_),
    .B(_044_),
    .Y(\mootop.Carry0 )
  );
  XNOR_g _154_ (
    .A(\mootop.Addend0 [3]),
    .B(_043_),
    .Y(\mootop.Sum0 [3])
  );
  NOR_g _155_ (
    .A(\mootop.Sum0 [1]),
    .B(1'h0),
    .Y(_045_)
  );
  AND_g _156_ (
    .A(\mootop.Sum0 [1]),
    .B(1'h0),
    .Y(_046_)
  );
  XNOR_g _157_ (
    .A(\mootop.Sum0 [1]),
    .B(1'h0),
    .Y(_047_)
  );
  NOR_g _158_ (
    .A(\mootop.Addend1 [0]),
    .B(_046_),
    .Y(_048_)
  );
  NOR_g _159_ (
    .A(_045_),
    .B(_048_),
    .Y(\mootop.rc1.C0 )
  );
  XNOR_g _160_ (
    .A(\mootop.Addend1 [0]),
    .B(_047_),
    .Y(NODEC[5])
  );
  NOR_g _161_ (
    .A(\mootop.Sum0 [2]),
    .B(\mootop.rc1.C0 ),
    .Y(_049_)
  );
  AND_g _162_ (
    .A(\mootop.Sum0 [2]),
    .B(\mootop.rc1.C0 ),
    .Y(_050_)
  );
  XNOR_g _163_ (
    .A(\mootop.Sum0 [2]),
    .B(\mootop.rc1.C0 ),
    .Y(_051_)
  );
  NOR_g _164_ (
    .A(\mootop.Addend1 [1]),
    .B(_050_),
    .Y(_052_)
  );
  NOR_g _165_ (
    .A(_049_),
    .B(_052_),
    .Y(\mootop.rc1.C1 )
  );
  XNOR_g _166_ (
    .A(\mootop.Addend1 [1]),
    .B(_051_),
    .Y(\mootop.Sum1 [1])
  );
  NOR_g _167_ (
    .A(\mootop.Sum0 [3]),
    .B(\mootop.rc1.C1 ),
    .Y(_053_)
  );
  AND_g _168_ (
    .A(\mootop.Sum0 [3]),
    .B(\mootop.rc1.C1 ),
    .Y(_054_)
  );
  XNOR_g _169_ (
    .A(\mootop.Sum0 [3]),
    .B(\mootop.rc1.C1 ),
    .Y(_055_)
  );
  NOR_g _170_ (
    .A(\mootop.Addend1 [2]),
    .B(_054_),
    .Y(_056_)
  );
  NOR_g _171_ (
    .A(_053_),
    .B(_056_),
    .Y(\mootop.rc1.C2 )
  );
  XNOR_g _172_ (
    .A(\mootop.Addend1 [2]),
    .B(_055_),
    .Y(\mootop.Sum1 [2])
  );
  NOR_g _173_ (
    .A(\mootop.Carry0 ),
    .B(\mootop.rc1.C2 ),
    .Y(_057_)
  );
  AND_g _174_ (
    .A(\mootop.Carry0 ),
    .B(\mootop.rc1.C2 ),
    .Y(_058_)
  );
  XNOR_g _175_ (
    .A(\mootop.Carry0 ),
    .B(\mootop.rc1.C2 ),
    .Y(_059_)
  );
  NOR_g _176_ (
    .A(\mootop.Addend1 [3]),
    .B(_058_),
    .Y(_060_)
  );
  NOR_g _177_ (
    .A(_057_),
    .B(_060_),
    .Y(\mootop.Carry1 )
  );
  XNOR_g _178_ (
    .A(\mootop.Addend1 [3]),
    .B(_059_),
    .Y(\mootop.Sum1 [3])
  );
  NOR_g _179_ (
    .A(\mootop.Sum1 [1]),
    .B(1'h0),
    .Y(_061_)
  );
  AND_g _180_ (
    .A(\mootop.Sum1 [1]),
    .B(1'h0),
    .Y(_062_)
  );
  XNOR_g _181_ (
    .A(\mootop.Sum1 [1]),
    .B(1'h0),
    .Y(_063_)
  );
  NOR_g _182_ (
    .A(\mootop.Addend2 [0]),
    .B(_062_),
    .Y(_064_)
  );
  NOR_g _183_ (
    .A(_061_),
    .B(_064_),
    .Y(\mootop.rc2.C0 )
  );
  XNOR_g _184_ (
    .A(\mootop.Addend2 [0]),
    .B(_063_),
    .Y(NODEC[4])
  );
  NOR_g _185_ (
    .A(\mootop.Sum1 [2]),
    .B(\mootop.rc2.C0 ),
    .Y(_065_)
  );
  AND_g _186_ (
    .A(\mootop.Sum1 [2]),
    .B(\mootop.rc2.C0 ),
    .Y(_066_)
  );
  XNOR_g _187_ (
    .A(\mootop.Sum1 [2]),
    .B(\mootop.rc2.C0 ),
    .Y(_067_)
  );
  NOR_g _188_ (
    .A(\mootop.Addend2 [1]),
    .B(_066_),
    .Y(_068_)
  );
  NOR_g _189_ (
    .A(_065_),
    .B(_068_),
    .Y(\mootop.rc2.C1 )
  );
  XNOR_g _190_ (
    .A(\mootop.Addend2 [1]),
    .B(_067_),
    .Y(NODEC[3])
  );
  NOR_g _191_ (
    .A(\mootop.Sum1 [3]),
    .B(\mootop.rc2.C1 ),
    .Y(_069_)
  );
  AND_g _192_ (
    .A(\mootop.Sum1 [3]),
    .B(\mootop.rc2.C1 ),
    .Y(_070_)
  );
  XNOR_g _193_ (
    .A(\mootop.Sum1 [3]),
    .B(\mootop.rc2.C1 ),
    .Y(_071_)
  );
  NOR_g _194_ (
    .A(\mootop.Addend2 [2]),
    .B(_070_),
    .Y(_072_)
  );
  NOR_g _195_ (
    .A(_069_),
    .B(_072_),
    .Y(\mootop.rc2.C2 )
  );
  XNOR_g _196_ (
    .A(\mootop.Addend2 [2]),
    .B(_071_),
    .Y(NODEC[2])
  );
  NOR_g _197_ (
    .A(\mootop.Carry1 ),
    .B(\mootop.rc2.C2 ),
    .Y(_073_)
  );
  AND_g _198_ (
    .A(\mootop.Carry1 ),
    .B(\mootop.rc2.C2 ),
    .Y(_074_)
  );
  XNOR_g _199_ (
    .A(\mootop.Carry1 ),
    .B(\mootop.rc2.C2 ),
    .Y(_075_)
  );
  NOR_g _200_ (
    .A(\mootop.Addend2 [3]),
    .B(_074_),
    .Y(_076_)
  );
  NOR_g _201_ (
    .A(_073_),
    .B(_076_),
    .Y(NODEC[0])
  );
  XNOR_g _202_ (
    .A(\mootop.Addend2 [3]),
    .B(_075_),
    .Y(NODEC[1])
  );
endmodule
